{% set name = "azure-datalake-store" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 5364d4445aab154a1c7cb10215629c3ce46ce5c7aaaf16071890c03fae53a035

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - cffi
    - requests >=2.20.0

test:
  imports:
    - azure.datalake.store

about:
  home: http://github.com/Azure/azure-data-lake-store-python
  license: MIT
  license_family: MIT
  license_file: License.txt
  summary: This project is the Python filesystem library for Azure Data Lake Store
  description: |
    A pure-python interface to the Azure Data-lake Storage system,
    providing pythonic file-system and file objects, seamless transition
    between Windows and POSIX remote paths, high-performance up- and down-loader.
  doc_url: http://github.com/Azure/azure-data-lake-store-python
  dev_url: http://github.com/Azure/azure-data-lake-store-python

extra:
  recipe-maintainers:
    - dillonroach
    - scopatz
    - costrouc
