travis:
  secure:
    BINSTAR_TOKEN: lG1z6pRqOuQ6c3toGuZ854hVLy37C2puKthaLdcHuECtBxb+FF2JCoPt7tDsCm3xHm0wnKO1SX1izLeYw4nfPoIfGaw1sz4HYSh7IoP0E81GeZfDG3lP0TGjwxD7hkMN7XYOKS2D+0PAvG/6qZjaTaqKhNl1a9n9odBM6XLdSvX0n85kt1UzINc0RYMsCF5htveOBaKOpIoidtNW5fJTcY+jPPiRUm+8XhpJHAdFoSYc0goyQX0P2TdrJ9zIGkSiV2T4eJtNW5whfSwQuPFfcamYPpD2J0tHS73DtqiDfZ7XbTKQCh33JV3IVgekaH9XTO+6LvZWphJ42N0uZojhmU8tShUUNh/ZkrgSux9pePqbllwlQdGg1gC7bEUxt0QYKw23ZaR4ohoTr+lls08Cm2TpL2Km2nj01ry0bNxS6CV+3ZUB7vFp2FqTRn6D9dTu3Lgz1WJnuOY5sRr0WzTpLVO77DRwgSbSvMYHwkzqXN/pZs979DlnafNeRU9bCcTMT1BE8EIoFDwrViTUI0SPxnJMT4ziMF8mpIzoPixPBNS0bDqcMox7GtmZkRwqKBbiPTMRCOhg7eEZdEuwJeUQuZE9V/BegkDlCnmBvUUgw8TQEcSrM2OP/0PsP5cO0kr0fVUBTypqCA2aEv1DMBqFmsMMQcUWoFWlDiizKjnJD+I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
